local views = require("utilitybelt.views")
views.Huds.Toaster.Add("Info", views.ToastType.Info)
views.Huds.Toaster.Add("Success", views.ToastType.Success)
views.Huds.Toaster.Add("Error", views.ToastType.Error)
views.Huds.Toaster.Add("Warning", views.ToastType.Warning)
